
var headerText = "bingo @ 120 ifb";

var footerText = "<a href='https://github.com/jeffehobbs/HTML5-bingo/' target='_blank'>Code available on github</a>";

var winText = "Nobel prize!";

var JSONBingo = {"squares": [
        {"square": "deep learning"},
        {"square": "\"hyper-parameters\""},
        {"square": "delayed prerec."},
        {"square": "noise bursts"},
        {"square": "limit plotting bug"},
        {"square": "gruffalo"},
        {"square": "reference to 7 TeV results"},
        {"square": "Release 23"},
        {"square": "CMS di-photon result"},
        {"square": "PUPPI"},
        {"square": "LFV is real"},
        {"square": "Chair reschedules coffee break"},
        {"square": "ttbar mis-modelling"},
        {"square": "stop sign at entrance B shown"},
        {"square": "twiki debate"},
        {"square": "Bayesian vs. frequentist debate"},
        {"square": "unclear truth particle definition"},
        {"square": "uncomfortable weasel joke"},
        {"square": "forward folding"},
        {"square": "&mu; > 60"},
        {"square": "\"hidden layers\""},
        {"square": "Run 3"},
        {"square": "controversial smoothing procedure"},
        {"square": "ICHEP 2018"},
        {"square": "\"why not jet reclustering?\""},
        {"square": "TLA"},
        {"square": "continuous integration"},
        {"square": "wide-eyed owl painting"},
        {"square": "TADA bump"},
        {"square": "too many sig figs"},
        {"square": "RD53"},
        {"square": "SUSY vs. EXO debate"},
        {"square": "new DAODfix"},
        {"square": "XeXe"},
        {"square": "plot from a thesis shown"},
        {"square": "MET tails"},
        {"square": "track calo-clusters"},
        {"square": "R=0.1 subjets"},
        {"square": "\"athena's not so bad\""},
        {"square": "mc16e"},
        {"square": "doctored muons"},
        {"square": "LEP"},
        {"square": "HEPData"},
        {"square": "new tau BDT"},
        {"square": "git sub-modules"},
        {"square": "H > &mu;&mu;"},
        {"square": "top-down vs. bottom-up debate"},
        {"square": "vidyo can't hear"}, 
        {"square": "Moriond 2018"},
        {"square": "low-&mu; data shown"}, 	
        {"square": "heavy ions"}
    ]
};
